services:
  nginx: 
    image: nginx:1.27.2-alpine  
    ports:
      - "8000:80"
    depends_on: 
      - hchexdoku 
    restart: "on-failure"
    volumes:
      - ./data/nginx-dev:/etc/nginx/conf.d
      - ./static:/static
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  hchexdoku:
    env_file: 
      - .env
    build: ./hchexdoku 
    expose: 
      - ${WEB_PORT}
    restart: "on-failure"
    command: sh -c "python manage.py collectstatic --no-input && gunicorn --bind :8000 --workers 3 hchexdoku.wsgi:application --reload --access-logfile -"
    volumes:  
      - ./hchexdoku:/hchexdoku
      - ./static:/static